const Types = {
  GET_ALL_IMAGES: "GET_ALL_IMAGES",
  GET_IMAGES_BY_HASHTAG: "GET_IMAGES_BY_HASHTAG",
  GET_IMAGES_DONE: "GET_IMAGES_DONE",
  UPLOAD_IMAGE: "UPLOAD_IMAGE",
  UPLOAD_IMAGE_DONE: "UPLOAD_IMAGE_DONE",
  UPLOAD_IMAGE_INIT: "UPLOAD_IMAGE_INIT"
};

export default Types;
